import BASE_ENV from "@/lib/config/baseEnv.js";
import TRANSFORMERS from "@/lib/config/transformers.js";
import {getRequiredEnv} from "@/lib/config/envUtils.js";


interface CustomEnv {
    INTERNAL_PORT: number;
    POSTGRES_DATABASE_URL: string,
    GOOGLE_CLIENT_ID: string,
    GOOGLE_REDIRECT_URI: string,
    GOOGLE_CLIENT_SECRET: string,
    SHOPIFY_CLIENT_ID: string,
    SHOPIFY_REDIRECT_URI: string,
    SHOPIFY_CLIENT_SECRET: string,
    INTERNAL_AUTH_COMMUNICATION_SECRET: string,
    
}

const CUSTOM_ENV: CustomEnv = {
    INTERNAL_PORT: getRequiredEnv('INTERNAL_PORT', TRANSFORMERS.NUMBER),
    POSTGRES_DATABASE_URL: getRequiredEnv('POSTGRES_DATABASE_URL', TRANSFORMERS.STRING),
    GOOGLE_CLIENT_ID: getRequiredEnv('GOOGLE_CLIENT_ID', TRANSFORMERS.STRING),
    GOOGLE_REDIRECT_URI: getRequiredEnv('GOOGLE_REDIRECT_URI', TRANSFORMERS.STRING),
    GOOGLE_CLIENT_SECRET: getRequiredEnv('GOOGLE_CLIENT_SECRET', TRANSFORMERS.STRING),
    SHOPIFY_CLIENT_ID: getRequiredEnv('SHOPIFY_CLIENT_ID', TRANSFORMERS.STRING),
    SHOPIFY_REDIRECT_URI: getRequiredEnv('SHOPIFY_REDIRECT_URI', TRANSFORMERS.STRING),
    SHOPIFY_CLIENT_SECRET: getRequiredEnv('SHOPIFY_CLIENT_SECRET', TRANSFORMERS.STRING),
    INTERNAL_AUTH_COMMUNICATION_SECRET: getRequiredEnv('INTERNAL_AUTH_COMMUNICATION_SECRET', TRANSFORMERS.STRING),
};

const ENV = {
    ...BASE_ENV,
    ...CUSTOM_ENV,
};

export default ENV;