services:
  auth-service:
    image: auth-service
    container_name: auth-service
    build:
      context: ../../backend/auth-service
      dockerfile: ../../backend/auth-service/Dockerfile.dev.dockerfile
    env_file:
      - ../../backend/auth-service/.env
    ports:
      - "4000:4000"
    networks:
      - auth-service-redis-db-network
      - auth-service-postgres-db-network
      - internal-network
    depends_on:
      auth-service-postgres-db:
        condition: service_healthy
      auth-service-redis-db:
        condition: service_healthy
        
  auth-service-postgres-db:
    image: postgres:14
    container_name: auth-service-postgres-db
    restart: always
    env_file:
      - ../../backend/auth-service/.env.auth-service-postgres-db
    volumes:
      - auth-service-postgres-db-data:/var/lib/postgresql/data
    networks:
      - auth-service-postgres-db-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\"'"]
      interval: 5s
      retries: 5
      start_period: 10s
  
  auth-service-redis-db:
    image: redis:alpine
    container_name: auth-service-redis-db
    restart: always
    volumes:
      - auth-service-redis-db-data:/data
    networks:
      - auth-service-redis-db-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5
      start_period: 5s
    command: ["redis-server", "--appendonly", "yes"]

  customer-dashboard:
    image: customer-dashboard
    container_name: customer-dashboard
    build:
      context: ../../frontend/customer-dashboard
      dockerfile: ../../frontend/customer-dashboard/Dockerfile.dev.dockerfile
      args:
        NODE_ENV: development
    env_file:
      - ../../frontend/customer-dashboard/.env
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - shopify-service
    networks:
      - customer-dashboard-network
    volumes:
      - ../../frontend/customer-dashboard:/app
      - /app/node_modules
      - /app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
  
  shopify-service:
    image: shopify-service
    container_name: shopify-service
    build:
      context: ../../backend/shopify-service
      dockerfile: ../../backend/shopify-service/Dockerfile.dev.dockerfile
      args:
        NODE_ENV: development
    env_file:
      - ../../backend/shopify-service/.env
    ports:
      - "4010:4010"
    networks:
      - shopify-service-redis-db-network
      - internal-network
    depends_on:
      shopify-service-redis-db:
        condition: service_healthy

  shopify-service-redis-db:
    image: redis:alpine
    container_name: shopify-service-redis-db
    restart: always
    volumes:
      - shopify-service-redis-db-data:/data
    networks:
      - shopify-service-redis-db-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5
      start_period: 5s
    command: [ "redis-server", "--appendonly", "yes" ]
  
volumes:
  auth-service-redis-db-data:
  auth-service-postgres-db-data:
  shopify-service-redis-db-data:
    
networks:
  auth-service-redis-db-network:
    driver: bridge
  auth-service-postgres-db-network:
    driver: bridge
  customer-dashboard-network:
    driver: bridge
  shopify-service-redis-db-network:
    driver: bridge
  internal-network:
    driver: bridge