services:
  auth-service:
    image: auth-service
    container_name: auth-service
    build:
      context: ../../backend/auth-service
      args:
        NODE_ENV: development
    env_file:
      - ../../backend/auth-service/.env
    ports:
      - "4000:4000"
    depends_on:
      - auth-service-db-postgres
      - auth-service-db-redis
    networks:
      - auth-service-network
      - customer-dashboard-network
    command: ["yarn", "dev"]
        
  auth-service-db-postgres:
    image: postgres:14
    container_name: auth-service-db-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth-service-db-postgres-data:/var/lib/postgresql/data
    networks:
      - auth-service-network

  auth-service-db-redis:
    image: redis:latest
    container_name: auth-service-db-redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - auth-service-network

  customer-dashboard:
    image: customer-dashboard
    container_name: customer-dashboard
    build:
      context: ../../frontend/customer-dashboard
      dockerfile: ../../frontend/customer-dashboard/Dockerfile.dev.dockerfile
      args:
        NODE_ENV: development
    env_file:
      - ../../frontend/customer-dashboard/.env
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
    networks:
      - customer-dashboard-network
    command: [ "yarn", "dev" ]

  shopify-service:
    image: shopify-service
    container_name: shopify-service
    build:
      context: ../../backend/shopify-service
      dockerfile: ../../backend/shopify-service/Dockerfile.dev.dockerfile
      args:
        NODE_ENV: development
    env_file:
      - ../../backend/shopify-service/.env
    ports:
      - "4001:4001"
    networks:
      - shopify-service_redis-network
    depends_on:
      - shopify-service-db-redis

  shopify-service-db-redis:
    image: redis:alpine
    container_name: shopify-service-db-redis
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - shopify-service_redis-data:/data
    networks:
      - shopify-service_redis-network
    command: [ "redis-server", "--appendonly", "yes" ]
  
volumes:
  auth-service-db-postgres-data:
  shopify-service_redis-data:
    
networks:
  auth-service-network:
    driver: bridge
  customer-dashboard-network:
    driver: bridge
  shopify-service_redis-network:
    driver: bridge