services:
  shopify-service:
    image: shopify-service
    container_name: shopify-service
    build:
      context: .
      dockerfile: Dockerfile.dev.dockerfile
    env_file:
      - ./.env
    ports:
      - "4010:4010"
    networks:
      - shopify-service-redis-db-network
    depends_on:
      shopify-service-redis-db:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      
  shopify-service-redis-db:
    image: redis:alpine
    container_name: shopify-service-redis-db
    restart: always
    volumes:
      - shopify-service-redis-db-data:/data
    networks:
      - shopify-service-redis-db-network
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5
      start_period: 5s


volumes:
  shopify-service-redis-db-data:
    
networks:
  shopify-service-redis-db-network:
    driver: bridge