services:
  server-template:
    image: server-template
    container_name: server-template
    build: .
    env_file:
      - ./.env
    ports:
      - "4001:4001"
    networks:
      - redis-network
    depends_on:
      - redis
      
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network
    command: ["redis-server", "--appendonly", "yes"]


networks:
  redis-network:
    driver: bridge
    
volumes:
  redis-data: